framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    validation:
        email_validation_mode: html5

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    assets: ~

    default_locale: '%env(APP_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
            - en

    profiler:
        dsn: 'file:%kernel.cache_dir%/profiler'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
